# Generated by Django 4.2.7 on 2024-01-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
