# Generated by Django 5.0 on 2024-01-18 20:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Start', models.TimeField()),
                ('End', models.TimeField()),
                ('Activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tripname', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('Itineraries', models.ManyToManyField(to='rest_api.itinerary')),
                ('Members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
