version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - NAME=postgres
      - USER=postgres
      - PASSWORD=postgres
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django-network
  nginx:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
        - django-network
networks:
  django-network:
    name: django-network