version: '3.8'
services:
  backend:
    build: ./backend
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
    - ./backend/.env
  nginx:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend